### ISSUE TITLE
 Failed to sign certificate request

### ISSUE THREAD

**Issue by aaronstutzer** [cloudflare/.github#12]
I installed cert-manager and origin-ca-issuer with helm and then created a secret, an originissuer, and a certificate.
my originissuer is verified & ready:
```
[
  {
    "lastTransitionTime": "2021-03-04T07:57:32Z",
    "message": "OriginIssuer verified and ready to sign certificates",
    "reason": "Verified",
    "status": "True",
    "type": "Ready"
  }
]
```

but in the certificaterequest i see the message:
```
Message:               Failed to sign certificate request: unable to sign request: Post "https://api.cloudflare.com/client/v4/certificates": net/http: invalid header field value "v1.0-FFFFF-FFFFFF\n" for key X-Auth-User-Service-Key
```

I re-deployed everything to make sure I did not forget anything but it is always the same issue.
my resources are:
```
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-ca-key
  namespace: istio-gateway
data:
  key: KEY
---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: istio-gateway
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: cloudflare-origin-ca-key
      key: key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.examle.com
  namespace: istio-gateway
spec:
  secretName: wildcard.example.com-tls
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-origin-ca-issuer
  dnsNames:
  - '*.example.com'
```

any ideas what my issue is?
